# SOPS Configuration for NET WORTH Tennis Ladder
# This file configures encryption for sensitive data

creation_rules:
  # Encrypt files containing sensitive information
  - path_regex: '\.env\.encrypted$'
    pgp: >-
      # Add PGP key fingerprints here for team members
      # Example format:
      # ABCDEF1234567890ABCDEF1234567890ABCDEF12
  - path_regex: 'secrets/.*\.toml$'
    pgp: >-
      # PGP keys for encrypted TOML files
  - path_regex: 'data/.*secrets\.toml$'
    pgp: >-
      # PGP keys for data directory secrets

# Key management
key_groups:
  - pgp:
      # Add team members' PGP key IDs
      # Format: [ "ABCDEF1234567890ABCDEF1234567890ABCDEF12" ]